### ISSUE TITLE
Rolling VPN detector

### ISSUE THREAD

**Issue by phinner** [Xpdustry/Nucleus#10]
The Mindustry community is experiencing heavy DDOS attacks, and it looks like the author attacks from non publicly listed cloud servers. Solution, use anti vpn services, but they are expensive so let's abuse the free tier of several ones:

- Ip quality score (5K/Month)
- vpnapi.io (1K/Day)
- iphub (1K/Day)
- ip2location.io (30K/Month)

Combining the listed servers, we can handle 3000 users per day.

> It is also advised to cache the flagged ips or store them in a database altogether.

**Comment by phinner** [comment]
Awful idea

**Comment by OnlyGergo** [comment]
Doesnt have to be: https://maxmind.github.io/minfraud-api-java/
not sure of accuracy but its free (and from a big ip info company) so why not give it a chance
